# Datos del proyecto en SonarQube
sonar.projectKey=Products-Analytics
sonar.projectName=Products-Analytics
sonar.projectVersion=1.0

# Servidor local en Docker Desktop
sonar.host.url=http://host.docker.internal:9005

# Carpetas base declaradas de forma independiente para evitar colisiones
sonar.sources=src
sonar.tests=tests

# Codificación estándar
sonar.sourceEncoding=UTF-8

# Exclusiones estrictas para evitar el rastreo doble
sonar.exclusions=.venv/**, tests/**, data/**, static/**, templates/**, seed.py

# Ruta exacta del reporte de cobertura
sonar.python.coverage.reportPaths=coverage.xml